# Author: Gurumoorthy Mohan, Kurian Benoy
version: "3.7"

x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
      - postgres
      - redis
  env_file: .env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - '7000:5000'
    environment:
      REDASH_WEB_WORKERS: 4
    labels:
      - traefik.http.routers.redash.entrypoints=insecure
      - traefik.http.routers.redash.rule=Host(`dev-redash.tech.fr`)
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.redash.middlewares=https-redirect@docker
      - traefik.http.routers.redashs.entrypoints=secure
      - traefik.http.routers.redashs.rule=Host(`dev-redash.tech.fr`)
      - traefik.http.routers.redashs.tls=true
      - traefik.http.routers.redashs.tls.certresolver=letsencrypt      
    networks:
      - web


  scheduler:
    <<: *redash-service
    command: scheduler
    networks:
      - web
    depends_on:
      - server

  scheduled_worker:
    <<: *redash-service
    networks:
      - web
    command: worker
  adhoc_worker:
    <<: *redash-service
    networks:
      - web    
    command: worker
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
    networks:
      - web    
    depends_on:
      - server
  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - web    
  postgres:
    image: postgres:9.6-alpine
    ports:
      - '7432:5432'
    restart: always
    env_file: .env
    networks:
      - web    
    volumes:
      - ./postgres/analytics:/var/lib/postgresql/data
  # Uncomment the following to enable redash mail server
  # email:
  #   image: djfarrelly/maildev
  #   ports:
  #     - "1080:80"
  #   restart: unless-stopped


networks:
  web:
    external: 
      name: web
  