# Author: Shibin Thomas
version: "3.7"

volumes:
  postgres:
  
networks:
  web:
    external: 
      name: web
     

services:
  keycloak-db:
    image: postgres:latest
    restart: always
    container_name: keycloak_db
    volumes:
      - ./postgres/keycloak:/data/postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_JDBC_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_JDBC_USER:-admin}
      POSTGRES_PASSWORD: ${KEYCLOAK_JDBC_PASSWORD:-changeme}
    ports:
      - 5431:5431
    networks:
      - web

  keycloak:
    image: jboss/keycloak:14.0.0
    restart: unless-stopped
    container_name: keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/formsflow-ai-realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=${KEYCLOAK_JDBC_DB:-keycloak}
      - DB_USER=${KEYCLOAK_JDBC_USER-admin}
      - DB_PASSWORD=${KEYCLOAK_JDBC_PASSWORD:-changeme}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER:-admin}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-changeme}
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    labels:
      - traefik.http.routers.keycloak.entrypoints=insecure
      - traefik.http.routers.keycloak.rule=Host(`dev-tls.tech.fr`)
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.keycloak.middlewares=https-redirect@docker
      - traefik.http.routers.keycloaks.entrypoints=secure
      - traefik.http.routers.keycloaks.rule=Host(`dev-tls.tech.fr`)
      - traefik.http.routers.keycloaks.tls=true
      - traefik.http.routers.keycloaks.tls.certresolver=letsencrypt      
    networks:
      - web

