# Author: Shibin Thomas
version: "3.7"
  
networks:
  web:
    external: 
      name: web
   

services:


  # Démarrage de Traefik sur le port 80 et 443
  traefik:
    image: traefik:chevrotin
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/conf/traefik.toml:/traefik.toml
      - ./traefik/conf/acme.json:/acme.json
    networks:
      - web